version: "3.9"
services:
  postgres_db_container:
    image: "postgres:latest"
    container_name: gotwitterclone-postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
  adminer_container:
    image: "adminer:latest"
    container_name: gotwitterclone-adminer
    restart: always
    ports:
      - 8080:8080
  redis_container:
    image: "redis:alpine"
    container_name: gotwitterclone-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
     - REDIS_REPLICATION_MODE=master