version: "3.9"
services:
  postgres_db_container:
    image: "postgres:latest"
    container_name: gotwitterclone-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  adminer_container:
    image: "adminer:latest"
    container_name: gotwitterclone-adminer
    restart: always
    ports:
      - 8080:8080

  redis_container:
    image: "redis:alpine"
    container_name: gotwitterclone-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - $PWD/docker-volumes/redis-data:/var/lib/redis
      - $PWD/docker-volumes/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
     - REDIS_REPLICATION_MODE=master