version: "3.9"
services:
  postgres_db_container:
    image: "postgres:latest"
    container_name: gotwitterclone-postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
  adminer_container:
    image: "adminer:latest"
    container_name: gotwitterclone-adminer
    restart: always
    ports:
      - 8080:8080
